name: Build Pages

on:
  push:
    branches: [ source ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          
      - name: Build
        run: |
          hexo clean
          hexo g
          git config --global user.email "1084926982@qq.com"
          git config --global user.name "Guiny-Time"
          hexo d