name: Build Pages

on:
  push:
    branches: [ source ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install nasm -y
          npm install -g hexo-cli
          npm install
          npm install hexo-all-minifier --save
          
      - name: Build
        run: |
          hexo clean
          git clone https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/Guiny-Time/Guiny-Time.github.io.git public -b main --depth=1 
          cd public
          git rm -rf .
          cd ..
          hexo g
          
      - name: Deploy
        run: |
          cd public
          git config --global user.email "1084926982@qq.com"
          git config --global user.name "Guiny-Time"
          git add .
          git commit -m "Automatic Deploy"
          git push -f
        
