name: Build Pages

on:
  push:
    branches: [ source ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install nasm -y
          npm install -g hexo-cli
          npm install
          npm install hexo-all-minifier --save

      - name: Build
        run: |
          hexo clean
          hexo g
          git config --global user.email "1084926982@qq.com"
          git config --global user.name "Guiny-Time"
          hexo d